CREATE TABLE variants (
  id SERIAL PRIMARY KEY,
  product_id INT REFERENCES products(id) ON DELETE CASCADE,
  additional_price NUMERIC(10, 2) DEFAULT 0.00,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE variant_translations (
  id SERIAL PRIMARY KEY,
  variant_id INT REFERENCES variants(id) ON DELETE CASCADE,
  language_id INT REFERENCES languages(id) ON DELETE CASCADE,
  name VARCHAR(100) NOT NULL
);
